name: expect_error
description: A testing utility for checking compilation errors
version: 1.0.0
repository: https://github.com/rrousselGit/expect_error

environment: 
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  analyzer: ^2.2.0
  build_test: ^2.1.3
  collection: ^1.15.0
  package_config: ^2.0.0
  path: ^1.8.0
  pubspec: ^2.0.1
  stack_trace: ^1.10.0
  test: ^1.17.12

dev_dependencies:
  test_api:
  test_core: